// hoahoang

export const ProductsAll = [
    {
        id: 1,
        title: "Bánh mì thập cẩm",
        priceRange: 15000,
        image: "bmithapcam.jpg",
        category: "ĐỒ ĂN",
      },
      {
        id: 2,
        title: "Bánh bao",
        priceRange: 5000,
        image: "banhbao.jpg",
        category: "ĐỒ ĂN",
      },
      {
        id: 3,
        title: "Xôi xéo",
        priceRange: 10000 ,
        image: "xoixeo.jpg",
        category: "ĐỒ ĂN",
      },
      {
        id: 4,
        title: "Phở bò",
        priceRange: 25000,
        image: "pho.jpg",
        category: "ĐỒ ĂN",
      },
      {
        id: 5,
        title: "Mì xúc xích",
        priceRange: 15000,
        image: "mixucxich.jpg",
        category: "ĐỒ ĂN",
      },
      {
        id: 6,
        title: "Mì trứng",
        priceRange: 15000,
        image: "mitrung.jpg",
        category: "ĐỒ ĂN",
      },
      {
        id: 7,
        title: "Xôi lạc vừng",
        priceRange: 10000 ,
        image: "xoilacvung.jpg",
        category: "ĐỒ ĂN",
      },
      {
        id: 8,
        title: "Bánh bao chay",
        priceRange: 5000,
        image: "banhbaochay.jpg",
        category: "ĐỒ ĂN",
      },
      {
        id: 9,
        title: "Bánh mì trứng",
        priceRange: 15000  ,
        image: "banhmitrung.jpg",
        category: "ĐỒ ĂN",
      },
      {
        id: 10,
        title: "Bánh bao xá xíu",
        priceRange: 25000,
        image: "banhbaoxaxiu.jpg",
        category: "ĐỒ ĂN",
      },
      {
        id: 11,
        title: "Bánh mì xúc xích",
        priceRange: 15000,
        image: "banhmixucxich.jpg",
        category: "ĐỒ ĂN",
      },
      {
        id: 12,
        title: "Cơm hộp",
        priceRange: 20000,
        image: "comhop.jpg",
        category: "ĐỒ ĂN",
      },
      // @hant Thực đơn đồ uống
      {
        id: 13,
        title: "Cà phê đen",
        priceRange: 15000 ,
        image: "capheden.jpg",
        category: "ĐỒ UỐNG",
      },
      {
        id: 14,
        title: "Cà phê sữa",
        priceRange: 20000,
        image: "caphesua.jpg",
        category: "ĐỒ UỐNG",
      },
      {
        id: 15,
        title: "Sinh tố xoài",
        priceRange: 20000,
        image: "sinhtoxoai.jpg",
        category: "ĐỒ UỐNG",
      },
      {
        id: 16,
        title: "Trà đào",
        priceRange: 20000,
        image: "tradao.jpg",
        category: "ĐỒ UỐNG",
      },
      {
        id: 17,
        title: "Trà hoa quả",
        priceRange: 15000,
        image: "nuoctraicay.jpg",
        category: "ĐỒ UỐNG",
      },
      {
        id: 18,
        title: "Trà chanh",
        priceRange: 15000,
        image: "trachanh.jpg",
        category: "ĐỒ UỐNG",
      },
      {
        id: 19,
        title: "Sữa nóng",
        priceRange: 10000,
        image: "sua.jpg",
        category: "ĐỒ UỐNG",
      },
      {
        id: 20,
        title: "Ca cao",
        priceRange: 15000,
        image: "cacao.jpg",
        category: "ĐỒ UỐNG",
      },
      {
        id: 21,
        title: "Trà gừng",
        priceRange: 10000,
        image: "tragung.jpg",
        category: "ĐỒ UỐNG",
      },
      {
        id: 22,
        title: "Trà lipton",
        priceRange: 20000,
        image: "tralipton.jpg",
        category: "ĐỒ UỐNG",
      },
      // @hant Thực đơn khác
      {
        id: 23,
        title: "Xúc xích rán",
        priceRange: 10000,
        image: "xucxich.jpg",
        category: "KHÁC",
      },
      {
        id: 24,
        title: "Lạp xưởng",
        priceRange: 15000,
        image: "lapxuong.jpg",
        category: "KHÁC",
      },
      {
        id: 25,
        title: "Khô gà lá chanh",
        priceRange: 20000,
        image: "khoga.jpg",
        category: "KHÁC",
      },
      {
        id: 26,
        title: "Khô bò",
        priceRange: 25000,
        image: "khobo.jpg",
        category: "KHÁC",
      },
      {
        id: 27,
        title: "Bánh tráng",
        priceRange: 10000 ,
        image: "banhtrang.jpg",
        category: "KHÁC",
      },
    ];